baseURL = ""
languageCode = "de-DE"
title = "Offene Daten Beratung"
enableEmoji = true

[params]
description = ""
cloudinary_url = "https://res.cloudinary.com/civicvision/image/upload"
mainSections = ["articles", "services"]
